# conda env create -f environment.yml
name: pmd_beamphysics-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - scipy>=1.0.0
  - matplotlib
  - h5py
  - python-dateutil
  # Developer
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pyyaml
  - jupyterlab>=3
  - nbconvert
  # Documentation
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings-python
  - pygments
  - pip
